Added note about immutability.
php-http/fig-standards pull request #16
Opened 2016-09-20 15:21 UTC by Nyholm

Is this a better place to warn about immutability?

This will fix #12

2016-09-20 16:27 UTC, sagikazarmark commented on proposed/http-client/http-client.md
> +     * reference as the Request object returned by an exception.
I would not mention exception specifically as the user might access the messages  from other sources. I would rather say something more general and mention exceptions as an example.

2016-09-20 16:28 UTC, sagikazarmark requested changes

2016-09-23 09:22 UTC, dbu commented on proposed/http-client/http-client.md
> +     * The client MAY do motifications to the Request before sending it. Because of PSR-7 objects are
/Because of PSR-7 objects are/Because PSR-7 objects are/

2016-09-23 09:22 UTC, dbu commented on proposed/http-client/http-client.md
> +     * immutable one cannot assume that the object passed to HttpClient::sendRequest will have the same
immutable, one

2016-09-23 09:23 UTC, dbu commented on proposed/http-client/http-client.md
> +     * reference as the Request object that is actually sent. For example the Request object that is
is reference the right word? could we just say "will be the same object"?

2016-09-23 09:43 UTC, dbu commented on proposed/http-client/http-client.md
> +     * have a different reference then the object passed here.
here you still say reference. maybe "the Request object that is returned ... MAY be a different object than the one passed to sendRequest, so `===` comparison is not possible.

and its "different than", not "different then"

2016-10-11 11:41 UTC, Nyholm commented
Thank you for the reviews. This PR is updated.

2016-10-11 11:43 UTC, dbu approved these changes
Looks good to me

2016-10-12 21:39 UTC, sagikazarmark requested changes

2016-10-12 21:39 UTC, sagikazarmark commented on proposed/http-client/http-client.md
> +     * be a different object than the one passed to sendRequest, so === comparison is not possible.
maybe say comparison by reference?

2016-10-12 21:39 UTC, sagikazarmark commented on proposed/http-client/http-client.md
> +     *
Maybe place a link to the relevant part of PSR-7?

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-7-http-message-meta.md#why-value-objects

Although not necessarily immutability is the main point there, but explains the WHY.

2016-10-13 07:47 UTC, Nyholm commented on proposed/http-client/http-client.md
> +     * be a different object than the one passed to sendRequest, so === comparison is not possible.
@dbu whats to move away from the word "reference" (https://github.com/php-http/fig-standards/pull/16#discussion_r80212953). I have no issues using that word as long as it makes sense and is easy to understand.

2016-10-13 11:27 UTC, sagikazarmark commented on proposed/http-client/http-client.md
> +     * be a different object than the one passed to sendRequest, so === comparison is not possible.
Hm, @dbu what's the downside of using the word "reference"? For me === comparison sounds like phrasing the same for people with less knowledge.

2016-10-15 11:12 UTC, dbu commented on proposed/http-client/http-client.md
> +     * be a different object than the one passed to sendRequest, so === comparison is not possible.
lets use reference. depending on how beginner-friendly we want to make it, we could have the === in parenthesis. but go with what you prefer @Nyholm. the important thing is that we mention, and people that are unsure what reference is probably won't get what we try to tell them anyways and have to figure it out the hard way. and anyways all existing PSR-7 implementations will likely already have that behaviour so we just better document the only possible way things can be with PSR-7

2016-10-15 11:35 UTC, Nyholm commented on proposed/http-client/http-client.md
> +     * be a different object than the one passed to sendRequest, so === comparison is not possible.
Thank you

2016-10-15 11:35 UTC, Nyholm commented
Thank you for your reviews

2016-10-15 11:35 UTC, merged